/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.JOptionPane;

/**
 *
 * @author mrrob
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    int accN;

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        signButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        jPanel1.setLayout(null);

        accTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTFActionPerformed(evt);
            }
        });
        accTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accTFKeyTyped(evt);
            }
        });
        jPanel1.add(accTF);
        accTF.setBounds(180, 80, 230, 30);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Acc. NO:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 80, 100, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 140, 100, 30);

        passTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTFActionPerformed(evt);
            }
        });
        passTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTFKeyTyped(evt);
            }
        });
        jPanel1.add(passTF);
        passTF.setBounds(180, 140, 230, 30);

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logIco.png"))); // NOI18N
        loginButton.setText("Login");
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(160, 220, 110, 40);

        signButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupIcon.png"))); // NOI18N
        signButton.setText("Sign Up");
        signButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signButton);
        signButton.setBounds(330, 220, 110, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgot_password-512.png"))); // NOI18N
        jButton2.setText("Forget Password");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(1);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 290, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        Signup s = new Signup();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String s = accTF.getText();
        pass = passTF.getText();
        //passTF.getP
        accN = Integer.parseInt(s);
        A t = Variable.check(accN, pass);
        if (t != null) {
            Home nw = new Home();
            nw.tempUser = t;
            nw.set();
            nw.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Wrong Acc No. or Password");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void accTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_accTFKeyTyped

    private void accTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTFActionPerformed
        // TODO add your handling code here:
        accTF.transferFocus();
    }//GEN-LAST:event_accTFActionPerformed
    String pass;
    private void passTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTFKeyTyped
        // TODO add your handling code here:
        pass = passTF.getText();
    }//GEN-LAST:event_passTFKeyTyped

    private void passTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTFActionPerformed
        // TODO add your handling code here:
        pass = passTF.getText();
        passTF.transferFocus();
    }//GEN-LAST:event_passTFActionPerformed

    private void accTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accTFKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_accTFKeyReleased

    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed
        // TODO add your handling code here:
        String s = accTF.getText();
        pass = passTF.getText();
        accN = Integer.parseInt(s);
        A t = Variable.check(accN, pass);
        if (t != null) {
            Home nw = new Home();
            nw.tempUser = t;
            nw.set();
            nw.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Wrong Acc No. or Password");
        }
    }//GEN-LAST:event_loginButtonKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Reset r=new Reset();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JButton signButton;
    // End of variables declaration//GEN-END:variables
}
