/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mrrob
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    String name = null;
    String contact = null;
    String email = null;
    String pass = null;
    String temPass = null;

    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        nameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contactTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tempPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        nameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTFKeyTyped(evt);
            }
        });
        jPanel1.add(nameTF);
        nameTF.setBounds(170, 90, 320, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 4, 310, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Full Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 90, 30);

        contactTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTFActionPerformed(evt);
            }
        });
        contactTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTFKeyTyped(evt);
            }
        });
        jPanel1.add(contactTF);
        contactTF.setBounds(170, 140, 320, 30);

        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });
        emailTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTFKeyTyped(evt);
            }
        });
        jPanel1.add(emailTF);
        emailTF.setBounds(170, 190, 320, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Contact Number:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(54, 184, 60, 40);

        passTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTFActionPerformed(evt);
            }
        });
        passTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTFKeyTyped(evt);
            }
        });
        jPanel1.add(passTF);
        passTF.setBounds(170, 240, 320, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 240, 70, 30);

        createButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/642233_edit_512x512.png"))); // NOI18N
        createButton.setText("Create");
        createButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        createButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createButtonKeyPressed(evt);
            }
        });
        jPanel1.add(createButton);
        createButton.setBounds(270, 370, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Re-Password:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 290, 110, 30);

        tempPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempPassActionPerformed(evt);
            }
        });
        tempPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tempPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempPassKeyTyped(evt);
            }
        });
        jPanel1.add(tempPass);
        tempPass.setBounds(170, 290, 320, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        Main nw = new Main();
        nw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    private void nameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTFKeyTyped
        // TODO add your handling code here:
        name = nameTF.getText();
    }//GEN-LAST:event_nameTFKeyTyped

    private void contactTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTFKeyTyped
        // TODO add your handling code here:
        contact = contactTF.getText();
    }//GEN-LAST:event_contactTFKeyTyped

    private void emailTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTFKeyTyped
        // TODO add your handling code here:
        email = emailTF.getText();
    }//GEN-LAST:event_emailTFKeyTyped

    private void passTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTFKeyTyped
        // TODO add your handling code here:
        pass = passTF.getText();
    }//GEN-LAST:event_passTFKeyTyped

    private void tempPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempPassKeyTyped
        // TODO add your handling code here:
        temPass = tempPass.getText();
        if(temPass.equals(pass)){
            tempPass.setBackground(Color.green);
        }
        else{
            tempPass.setBackground(Color.red);
        }
    }//GEN-LAST:event_tempPassKeyTyped

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        name = nameTF.getText();
        contact = contactTF.getText();
        email = emailTF.getText();
        pass = passTF.getText();
        temPass = tempPass.getText();
        if (nameTF.getText().isEmpty() || contactTF.getText().isEmpty() || emailTF.getText().isEmpty() || passTF.getText().isEmpty()) {
            nameTF.setText("");
            contactTF.setText("");
            emailTF.setText("");
            passTF.setText("");
            tempPass.setText("");
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields");
        } else if (!pass.matches(temPass)) {
            nameTF.setText("");
            contactTF.setText("");
            emailTF.setText("");
            passTF.setText("");
            tempPass.setText("");
            JOptionPane.showMessageDialog(null, "Both Password Field not matched");
        } else {
            try {
                nameTF.setText("");
                contactTF.setText("");
                emailTF.setText("");
                passTF.setText("");
                tempPass.setText("");
                Variable.accN++;
                String s = Integer.toString(Variable.accN);
                JOptionPane.showMessageDialog(null, "Your Account Number: " + s + "\nUse This to log in to your account");
                Variable.data.add(new A(name, contact, email, pass, Variable.accN));
                Variable.save();
            } catch (IOException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
        nameTF.transferFocus();
    }//GEN-LAST:event_nameTFActionPerformed

    private void contactTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTFActionPerformed
        // TODO add your handling code here:
        contactTF.transferFocus();
    }//GEN-LAST:event_contactTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
        emailTF.transferFocus();
    }//GEN-LAST:event_emailTFActionPerformed

    private void passTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTFActionPerformed
        // TODO add your handling code here:
        passTF.transferFocus();
    }//GEN-LAST:event_passTFActionPerformed

    private void tempPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempPassActionPerformed
        // TODO add your handling code here:
        tempPass.transferFocus();
        
    }//GEN-LAST:event_tempPassActionPerformed

    private void createButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createButtonKeyPressed
        // TODO add your handling code here:
        if (nameTF.getText().isEmpty() || contactTF.getText().isEmpty() || emailTF.getText().isEmpty() || passTF.getText().isEmpty()) {
            nameTF.setText("");
            contactTF.setText("");
            emailTF.setText("");
            passTF.setText("");
            tempPass.setText("");
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields");
        } else if (!pass.matches(temPass)) {
            nameTF.setText("");
            contactTF.setText("");
            emailTF.setText("");
            passTF.setText("");
            tempPass.setText("");
            JOptionPane.showMessageDialog(null, "Both Password Field not matched");
        } else {
            try {
                nameTF.setText("");
                contactTF.setText("");
                emailTF.setText("");
                passTF.setText("");
                tempPass.setText("");
                Variable.accN++;
                String s = Integer.toString(Variable.accN);
                JOptionPane.showMessageDialog(null, "Your Account Number: " + s + "\nUse This to log in to your account");
                Variable.data.add(new A(name, contact, email, pass, Variable.accN));
                Variable.save();
            } catch (IOException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createButtonKeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Main nw = new Main();
        nw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tempPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempPassKeyReleased
        // TODO add your handling code here:
        pass = passTF.getText();
        temPass = tempPass.getText();
        if(temPass.equals(pass)){
            tempPass.setBackground(Color.green);
        }
        else{
            tempPass.setBackground(Color.red);
        }
    }//GEN-LAST:event_tempPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactTF;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField emailTF;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JPasswordField tempPass;
    // End of variables declaration//GEN-END:variables

}
